plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.google.protobuf' version '0.9.5'
}

group = 'com.github.vslyusarev.warehousealerts'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    api 'com.google.protobuf:protobuf-java:4.33.0'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.33.0'
    }
}


java {
    withSourcesJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }

    repositories {
        mavenLocal()
    }
}

