syntax = "proto3";

package warehouse_alerts;

import "google/protobuf/timestamp.proto";

option java_package = 'com.github.vslyusarev.warehousealerts.shared';
option java_multiple_files = true;

enum SensorType {
  TEMPERATURE = 0;
  HUMIDITY = 1;
};

message WarehouseMessageKey {
  string warehouseId = 1;
  string sensorId = 2;
}

message WarehouseMessagePayload {
  string warehouseId = 1;
  google.protobuf.Timestamp timestamp = 2;
  SensorType sensorType = 3;
  string sensorId = 4;
  int32 value = 5;
}